---
# tasks file for roles/cluster-prep
- name: Disable SWAP
  shell: |
    swapoff -a

- name: Remove Swap from fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/swap.img'

- name: Forwarding IPv4 and letting iptables see bridged traffic (1/3)
  copy:
    src: k8s.conf.modules
    dest: /etc/modules-load.d/k8s.conf

- name: Forwarding IPv4 and letting iptables see bridged traffic (2/3)
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Forwarding IPv4 and letting iptables see bridged traffic (3/3)
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Install Container runtime
  apt:
    pkg:
    - containerd
    - apt-transport-https
    state: present

- name: Configure Contianerd (1/2)
  file:
    path: /etc/containerd
    state: directory

- name: Configure Containerd (2/2)
  shell: |
    containerd config default > /etc/containerd/config.toml

- name: Start and Enable Conatinerd service
  service:
    name: containerd
    state: started
    enabled: yes

- name: Add Kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Enable Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install Container runtime
  apt:
    pkg:
    - kubelet
    - kubeadm
    state: present
    
- name: Install kubectl
  apt:
    name: kubectl
    state: present
  when: "'master' in inventory_hostname"
