---
- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['kube_master'][0] }}"

- name: Save the command
  set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join the worker nodes to the cluster
  shell: "{{ kubeadm_join }}"
